import React from 'react';
import classes from '../ProductData/ProductData.module.css';
import irishflower from '../../assets/plantimages/succulent/Irishflower.jpg';
import bluechalksticks from '../../assets/plantimages/succulent/bluechalksticks.jpg';
import coppersedum from '../../assets/plantimages/succulent/coppersedum.jpg';
import gollumjade from '../../assets/plantimages/succulent/gollumjade.jpg';
import haworthiafasciata from '../../assets/plantimages/succulent/haworthiafasciata.jpg';
import sedum from '../../assets/plantimages/succulent/sedum.jpg';
import auroraborealis from '../../assets/plantimages/succulent/auroraborealis.jpg';
import pencilcactus from '../../assets/plantimages/succulent/pencilcactus.jpg';
import spooncactus from '../../assets/plantimages/succulent/spooncactus.jpg';
import kalanchoemarmorata from '../../assets/plantimages/succulent/kalanchoemarmorata.jpg';
import kleidostylis from '../../assets/plantimages/succulent/kleidostylis.jpg';
import lawyerstongue from '../../assets/plantimages/succulent/lawyerstongue.jpg';
import paddleplant from '../../assets/plantimages/succulent/paddleplant.jpg';
import thaiplant from '../../assets/plantimages/indoor/thaiplant.jpg';
import handingpothos from '../../assets/plantimages/indoor/handingpothos.jpg';
import bamboo from '../../assets/plantimages/indoor/bamboo.jpg';
import snakeplant from '../../assets/plantimages/indoor/snakeplant.jpg';
import dracaenadragon from '../../assets/plantimages/indoor/dracaenadragon.jpg';
import lemoncypress from '../../assets/plantimages/indoor/lemoncypress.jpg';
import sansevieria from '../../assets/plantimages/indoor/sansevieria.jpg';
import schefflera from '../../assets/plantimages/indoor/schefflera.jpg';
import rosemary from '../../assets/plantimages/outdoor/rosemary.jpg';
import basil from '../../assets/plantimages/outdoor/basil.jpg';
import williamsplant from '../../assets/plantimages/outdoor/williamsplant.jpg';
import sanguinaria from '../../assets/plantimages/outdoor/sanguinaria.jpg';
import pansy from '../../assets/plantimages/outdoor/pansy.jpg';
import marjoram from '../../assets/plantimages/outdoor/marjoram.jpg';
import periwinkle from '../../assets/plantimages/outdoor/periwinkle.jpg';
import mint from '../../assets/plantimages/outdoor/mint.jpg';
import rose from '../../assets/plantimages/outdoor/rose.jpg';

export const getProducts = () => {
  const products = [
    {
      id: 'irishflower',
      name: 'Irish Flower',
      category: 'Succulent',
      price: 35,
      description: '',
      image: irishflower,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'bluechalksticks',
      name: 'Bluechalk Sticks',
      category: 'Succulent',
      price: 45,
      description: '',
      image: bluechalksticks,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'coppersedum',
      name: 'Copper Sedum',
      category: 'Succulent',
      price: 45,
      description: '',
      image: coppersedum,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'gollumjade',
      name: 'Gollum Jade',
      category: 'Succulent',
      price: 45,
      description: '',
      image: gollumjade,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'haworthiafasciata',
      name: 'Haworthia Fasciata',
      category: 'Succulent',
      price: 45,
      description: '',
      image: haworthiafasciata,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'sedum',
      name: 'Sedum',
      category: 'Succulent',
      price: 45,
      description: '',
      image: sedum,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'auroraborealis',
      name: 'Aurora Borealis',
      category: 'Succulent',
      price: 45,
      description: '',
      image: auroraborealis,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'pencilcactus',
      name: 'Pencil Cactus',
      category: 'Succulent',
      price: 45,
      description: '',
      image: pencilcactus,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'spooncactus',
      name: 'Spoon Cactus',
      category: 'Succulent',
      price: 45,
      description: '',
      image: spooncactus,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'kalanchoemarmorata',
      name: 'Kalanchoe Marmorata',
      category: 'Succulent',
      price: 45,
      description: '',
      image: kalanchoemarmorata,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'kleidostylis',
      name: 'Kleidostylis',
      category: 'Succulent',
      price: 45,
      description: '',
      image: kleidostylis,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: "lawyer'stongue",
      name: "Lawyer's Tongue",
      category: 'Succulent',
      price: 45,
      description: '',
      image: lawyerstongue,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'paddleplant',
      name: 'Paddle Plant',
      category: 'Succulent',
      price: 45,
      description: '',
      image: paddleplant,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'thaiplant',
      name: 'Thai Plant',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: thaiplant,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'handingpothos',
      name: 'Handing Pothos',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: handingpothos,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'bamboo',
      name: 'Bamboo',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: bamboo,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'snakeplant',
      name: 'Snake Plant',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: snakeplant,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'dracaenadragon',
      name: 'Dracaena Dragon',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: dracaenadragon,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'lemoncypress',
      name: 'Lemon Cypress',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: lemoncypress,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'sansevieria',
      name: 'Sansevieria',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: sansevieria,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'schefflera',
      name: 'Schefflera',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: schefflera,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'rosemary',
      name: 'Rosemary',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: rosemary,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'basil',
      name: 'Basil',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: basil,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: "william'splant",
      name: "William's Plant",
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: williamsplant,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'sanguinaria',
      name: 'Sanguinaria',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: sanguinaria,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'pansy',
      name: 'Pansy',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: pansy,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'marjoram',
      name: 'Marjoram',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: marjoram,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'periwinkle',
      name: 'Periwinkle',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: periwinkle,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'mint',
      name: 'Mint',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: mint,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'rose',
      name: 'Rose',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: rose,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
  ];

  const featuredProducts = [
    {
      id: 'bluechalksticks',
      name: 'Bluechalk Sticks',
      category: 'Succulent',
      price: 45,
      description: '',
      image: bluechalksticks,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'coppersedum',
      name: 'Copper Sedum',
      category: 'Succulent',
      price: 45,
      description: '',
      image: coppersedum,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'bamboo',
      name: 'Bamboo',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: bamboo,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'snakeplant',
      name: 'Snake Plant',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: snakeplant,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'marjoram',
      name: 'Marjoram',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: marjoram,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'periwinkle',
      name: 'Periwinkle',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: periwinkle,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'mint',
      name: 'Mint',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: mint,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
  ];

  const recentProducts = [
    {
      id: 'haworthiafasciata',
      name: 'Haworthia Fasciata',
      category: 'Succulent',
      price: 45,
      description: '',
      image: haworthiafasciata,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'snakeplant',
      name: 'Snake Plant',
      category: 'Indoor Plants',
      price: 45,
      description: '',
      image: snakeplant,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'periwinkle',
      name: 'Periwinkle',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: periwinkle,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
    {
      id: 'mint',
      name: 'Mint',
      category: 'Outdoor Plants',
      price: 45,
      description: '',
      image: mint,
      colorOptions: ['grey', 'yellow', 'green'],
      sizeOptions: ['XS', 'S', 'M', 'L', 'XL', '2XL', '3XL'],
    },
  ];

  // Function to get product by ID
  const getProductById = (id) => {
    return products.find((product) => product.id === id) || null;
  };

  return { products, featuredProducts, recentProducts, getProductById };
};
