/** Default editable website copy + media — override from /dashboard */

export const DEFAULT_SITE_CONTENT = {
  hero: {
    eyebrow: 'Alexandria greenhouse',
    eyebrowAr: 'صوبة الإسكندرية',
    tagline: 'Living greens, styled for your home.',
    taglineAr: 'خضرة حيّة… بأناقة لبيتك.',
    cta: 'Shop the collection',
    ctaAr: 'تسوّق المجموعة',
    bambooImage: '',
    bambooEyebrow: 'Best seller',
    bambooEyebrowAr: 'الأكثر مبيعاً',
    bambooTitle: 'Lucky bamboo',
    bambooTitleAr: 'خيزران الحظ',
    snakeImage: '',
    snakeEyebrow: 'Almost unkillable',
    snakeEyebrowAr: 'يصعب قتلها',
    snakeTitle: 'Snake plant',
    snakeTitleAr: 'نبتة الثعبان',
    trioImage1: '',
    trioImage2: '',
    trioImage3: '',
    trioEyebrow: 'Bundle & save',
    trioEyebrowAr: 'باقة ووفّر',
    trioTitle: 'Succulent Trio Deal',
    trioTitleAr: 'عرض ثلاثي الصباريات',
    pothosImage: '',
    pothosEyebrow: 'Trailing favorite',
    pothosEyebrowAr: 'المفضل المتدلي',
    pothosTitle: 'Hanging pothos',
    pothosTitleAr: 'بثوس معلّق',
  },
  home: {
    featuredTitle: 'Bestsellers from the greenhouse',
    featuredSubtitle: 'The plants Alexandria keeps coming back for',
    recentTitle: 'New from the nursery',
    recentSubtitle: 'Fresh stock, ready for your space',
    socialTitle: 'Life inside the greenhouse',
    socialSubtitle:
      'Nursery visits, careful repotting, and packing — the real process behind every plant we send.',
    socialImage: '',
    discountImage: '',
    browseLabel: 'Browse',
    browseTitle: 'Find your green match',
    browseQuote: 'Every space deserves a plant that feels like it belongs.',
    bundlesEyebrow: 'Bundles & offers',
    bundlesTitle: 'More green, smarter price',
    bundlesSubtitle:
      'Curated plant deals — styled sets with real savings when you take them together.',
    bundles: [
      {
        id: 'desert',
        name: 'Desert Calm Trio',
        nameAr: 'ثلاثي هدوء الصحراء',
        desc: 'Three low-water succulents for shelves that love the sun.',
        descAr: 'ثلاث صباريات قليلة الري للرفوف المحبّة للشمس.',
        image: '',
        price: 115,
        compare: 135,
        save: 15,
        to: '/shop?category=Succulent',
      },
      {
        id: 'indoor',
        name: 'Indoor Starter Set',
        nameAr: 'طقم البداية الداخلي',
        desc: 'Easy greens for bright rooms and soft corners.',
        descAr: 'خضرة سهلة للغرف المضيئة والزوايا الناعمة.',
        image: '',
        price: 120,
        compare: 135,
        save: 12,
        to: '/shop?category=Indoor%20Plants',
      },
      {
        id: 'herbs',
        name: 'Herb Balcony Bundle',
        nameAr: 'باقة أعشاب الشرفة',
        desc: 'Sun-loving herbs ready for your balcony kitchen.',
        descAr: 'أعشاب محبّة للشمس جاهزة لمطبخ شرفتك.',
        image: '',
        price: 120,
        compare: 135,
        save: 10,
        to: '/shop?category=Outdoor%20Plants',
      },
    ],
    scentEyebrow: 'Scented corner',
    scentTitle: 'Herbs that smell like home',
    scentSubtitle: 'Fresh aromatic plants for kitchens and sunny ledges.',
    scents: [
      {
        id: 'mint',
        name: 'Garden Mint',
        nameAr: 'نعناع الحديقة',
        desc: 'Cool, clean aroma for kitchens and morning tea.',
        descAr: 'رائحة باردة ونظيفة للمطابخ وشاي الصباح.',
        image: '',
        price: 45,
        to: '/shop?category=Outdoor%20Plants',
      },
      {
        id: 'basil',
        name: 'Sweet Basil',
        nameAr: 'ريحان حلو',
        desc: 'Classic kitchen herb with a bright, peppery scent.',
        descAr: 'عشبة مطبخ كلاسيكية برائحة مشرقة.',
        image: '',
        price: 45,
        to: '/shop?category=Outdoor%20Plants',
      },
      {
        id: 'rosemary',
        name: 'Rosemary',
        nameAr: 'إكليل الجبل',
        desc: 'Woody fragrance for sunny balconies and cooking.',
        descAr: 'رائحة خشبية للشرفات المشمسة والطبخ.',
        image: '',
        price: 45,
        to: '/shop?category=Outdoor%20Plants',
      },
    ],
    giftsEyebrow: 'Gifting',
    giftsTitle: 'Ready-to-give plant sets',
    giftsSubtitle: 'Thoughtful greens packed for birthdays, homes, and desks.',
    gifts: [
      {
        id: 'new-home',
        name: 'New home gift set',
        nameAr: 'طقم هدية منزل جديد',
        desc: 'A welcoming indoor plant, ceramic pot, and greeting card.',
        descAr: 'نبتة داخلية ترحيبية، أصيص سيراميك، وبطاقة تهنئة.',
        image: '',
        price: 220,
        compare: 260,
        parts: 'Plant, Pot, Card',
        partsAr: 'نبتة، أصيص، بطاقة',
        to: '/shop',
      },
      {
        id: 'desk-calm',
        name: 'Desk calm set',
        nameAr: 'طقم هدوء المكتب',
        desc: 'A compact succulent, pot, and soft wrap for workspaces.',
        descAr: 'صبار مدمج، أصيص، وتغليف ناعم لمساحات العمل.',
        image: '',
        price: 180,
        compare: 210,
        parts: 'Plant, Pot, Wrap',
        partsAr: 'نبتة، أصيص، تغليف',
        to: '/shop?category=Succulent',
      },
      {
        id: 'balcony',
        name: 'Balcony starter',
        nameAr: 'بداية الشرفة',
        desc: 'Outdoor greens with wrap and a handwritten card.',
        descAr: 'خضرة خارجية مع تغليف وبطاقة مكتوبة بخط اليد.',
        image: '',
        price: 195,
        compare: 230,
        parts: 'Plant, Wrap, Card',
        partsAr: 'نبتة، تغليف، بطاقة',
        to: '/shop?category=Outdoor%20Plants',
      },
    ],
  },
  about: {
    eyebrow: "Egypt's plant atelier",
    title: 'Grown with patience. Delivered with care.',
    body: 'Nabat began in Alexandria with a simple belief: a home should feel like it can breathe. We spend so much of life indoors — and the air we share with living greens shapes how calm, clear, and alive a room feels.\n\nSo we built a small greenhouse atelier for modern Egyptian homes. Quiet indoor plants, sun-loving outdoor companions, and desert succulents — each chosen not only for beauty, but to settle gently into everyday life.\n\nEvery plant leaves our nursery healthy, carefully prepared, and ready for your space. When greens thrive beside you, the room softens — and so does the air you live in.',
    bodyAr:
      'بدأت نبات في الإسكندرية من إيمان بسيط: أن المنزل يجب أن يشعر وكأنه يتنفّس. نقضي كثيراً من حياتنا في الداخل — والهواء الذي نشاركه مع الخضرة الحيّة يشكّل هدوء الغرفة ووضوحها وحيويتها.\n\nلهذا أنشأنا مرسم صوبة صغير للمنازل المصرية العصرية. نباتات داخلية هادئة، رفقاء خارجيون يحبّون الشمس، وصباريات صحراوية — كلّها مختارة لا لجمالها فقط، بل لتستقر بلطف في يومياتنا.\n\nكل نبتة تغادر مشتلنا صحيحة ومُجهّزة بعناية وجاهزة لمساحتك. حين تنمو الخضرة بجانبك، ترقّ الغرفة — ويرقّ معها الهواء الذي نعيش فيه.',
    image: '',
  },
  contact: {
    eyebrow: 'Say hello',
    title: "We're here for your plants",
    subtitle: 'Orders, care tips, or custom picks — write us anytime.',
    locationLabel: 'Location',
    location: 'Alexandria, Egypt',
  },
  footer: {
    tagline: 'Living greens, delivered with care',
  },
  shop: {
    bannerTitle: 'Shop',
    bannerEyebrow: 'The collection',
    bannerImage: '',
  },
  store: {
    phone: '01270545289',
    email: 'youssefashour19@gmail.com',
    city: 'Alexandria',
    country: 'Egypt',
    shippingFee: 50,
    paymentNumber: '01270545289',
  },
};

export const DEFAULT_CATEGORIES = [
  {
    id: 'succulent',
    name: 'Succulent',
    nameAr: 'صباريات',
    description: 'Sculptural desert greens that thrive on little water',
    descriptionAr: 'خضرة صحراوية منحوتة تنمو بقليل من الري',
    image: '',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'indoor-plants',
    name: 'Indoor Plants',
    nameAr: 'نباتات داخلية',
    description: 'Calm foliage for bright rooms and soft corners',
    descriptionAr: 'أوراق هادئة للغرف المضيئة والزوايا الناعمة',
    image: '',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'outdoor-plants',
    name: 'Outdoor Plants',
    nameAr: 'نباتات خارجية',
    description: 'Sun-loving herbs and blooms for balconies and gardens',
    descriptionAr: 'أعشاب وأزهار محبّة للشمس للشرفات والحدائق',
    image: '',
    sortOrder: 3,
    isActive: true,
  },
];
